# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TheMovieDB' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TheMovieDB
  pod 'RNVectorIcons', :path => 'node_modules/react-native-vector-icons'

  target 'TheMovieDB-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TheMovieDBTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TheMovieDB-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TheMovieDB-tvOS

  target 'TheMovieDB-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
